version: '3.4'

services:
  storageadapter:
    image: horeichcontainers.azurecr.io/storageadapter-v2:latest
    build:
      context: ./StorageAdapter
      dockerfile: Dockerfile
    environment:
      - PCS_KEYVAULT_NAME
      - PCS_AAD_APPID
      - PCS_AAD_APPSECRET
      - ASPNETCORE_ENVIRONMENT
    networks:
      docker-net:
        ipv4_address: 172.18.1.1

  iotbridge:
    image: horeichcontainers.azurecr.io/iotbridge-v2:latest
    build:
      context: ./IoTBridge
      dockerfile: Dockerfile
    environment:
      - PCS_KEYVAULT_NAME
      - PCS_AAD_APPID
      - PCS_AAD_APPSECRET
      - ASPNETCORE_ENVIRONMENT
    networks:
      docker-net:
        ipv4_address: 172.18.1.2
    depends_on:
      - storageadapter-v2

  coapendpoint:
    image: horeichcontainers.azurecr.io/coapendpoint:latest   
    build:
      context: ./CoAPEndpoint
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT
    ports:
      - "5683:5683/udp"
    networks:
      docker-net:
        ipv4_address: 172.18.1.3
    depends_on:
      - iotbridge-v2

networks:
  docker-net:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
          
